[package]
name = "bench-uring"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-uring = "0.5.0"
monoio = "0.2"
lazy-regex = { version = "3.4.1", default-features = false, features = ["lite"] }

[dev-dependencies]
